services:
  nuxt:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    expose:
      - 3000
    command: "node /app/server/index.mjs"
    restart: always
    env_file: ./.env

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 3000:80
    depends_on:
      - nuxt
