services:
  nuxt:
    build: ./app
    expose:
      - 3000
    command:
      "node .output/server/index.mjs"
    restart: always
    env_file:
      ./app/.env

  nginx:
    build: ./nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
